### ISSUE TITLE
Some tests fail on windows.

### ISSUE THREAD

**Issue by Devasta** [ballsteve/xrust#21]
For example:

---- impls::graphitem::tests::xsl_pretty_print stdout ----
thread 'impls::graphitem::tests::xsl_pretty_print' panicked at 'assertion failed: `(left == right)`
  left: `"<Test>\r\n  <data role='test'>\r\n    <deeper>one</deeper>\r\n  </data>\r\n  <data role='test'>\r\n    <deeper>two</deeper>\r\n  </data>\r\n</Test>"`,
 right: `"<Test>\n  <data role='test'>\n    <deeper>one</deeper>\n  </data>\n  <data role='test'>\n    <deeper>two</deeper>\n  </data>\n</Test>"`', src\impls\graphitem.rs:3122:7

The test itself is fine, its only the EOL characters causing trouble, but would be good to adjust those.

**Comment by ballsteve** [comment]
I'm looking into that one. Something's not quite right with the serialise code.

**Comment by ballsteve** [comment]
At some stage we may need to introduce a Canonical XML output option

**Comment by Devasta** [comment]
Closing this, the test in question no longer exists.
