### ISSUE TITLE
XSLT 1

### ISSUE THREAD

**Issue by liamquin** [ballsteve/xrust#43]
A note here - you might not mean it literally, but implementing XSLT 1 and then moving to 3 is extra work you[ll need to undo: XSLT 1 is built on top of nodesets and XSLT 2 and later on top of sequences. In XSLT 4 there are also record types :)

Probably you know this already and are just meaning, roughly the equivalent of XSLT 1.

Of course, FLWOR operates on tuple streams, it's a join, so you've necessarily gone beyond node sets, but i thought i'd better say something. Feel free to close this issue right away - hey, it's awesome to close issues! i'd have messaged you on mastodon instead but it doesn't seem to be working.

**Comment by ballsteve** [comment]
No, it is not meant literally.

And yes, you are right: we do know that and are meaning to implement a processor that is roughly equivalent to XSLT 1. By that we mean to implement data structures and features that at least emulate what can be done in XSLT 1. We are definitely not going to implement XSLT 1 features that are not useful in XSLT 2, 3, or 4.

We're already doing things that cannot be done in XSLT 1.

My plan is to close the issue when we achieve XSLT 1 feature completeness.

**Comment by liamquin** [comment]
Awesome, thanks

**Comment by ballsteve** [comment]
Documentation in the next release will be reviewed to ensure that it is clear that we are NOT aiming for XPath/XSLT 1.0 compatibility
