### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Protoculos** [ballsteve/xrust#52]
Sorry, but without documentation and examples, it is completely incomprehensible how this can be used.

**Comment by ballsteve** [comment]
Fair enough. A lot of the work is new (parser combinator, tree implementations), so the documentation is a bit sparse at the moment.

We will work on adding more examples and a tutorial.

BTW, do you have particular interest in this crate? What would you want to use it for?

**Comment by Protoculos** [comment]
I need this crate for web scraping. I'm new with rust and I tried using a crate but couldn't.
You need at least a simple example.
How to create a document.
How to use xpath to find required data.
I used golang library before. 
https://github.com/antchfx/htmlquery
Simple examples will help to use crate.

**Comment by Protoculos** [comment]
This is an example of chatGPT v4 with xrust crate, but there is an error somewhere. Can you fix it? You can also use this example in the documentation.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2023fb094de183724239033c02f51116

**Comment by ballsteve** [comment]
I've added an example, 'issue_52', that successfully runs and produces the desired result. Well, there is one error that should be raised as a defect.

The example is in the branch issue_52. This will be a pull request and merged as soon as possible.

**Comment by ballsteve** [comment]
Pull Request merged
