### ISSUE TITLE
Does xrust support namespace?

### ISSUE THREAD

**Issue by ballsteve** [ballsteve/xrust#58]
### Discussed in https://github.com/ballsteve/xrust/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **tacoberu** October 21, 2023</sup>
Hello.

I would like to use xrust in my library for xslt transformations. But somehow I can't force namespaces to be used on the output. Wouldn't there be a sample somewhere?

Thanks for the direction.</div>

**Comment by tacoberu** [comment]
In the [attachment](https://github.com/ballsteve/xrust/files/13245411/xrust-58.zip) I attach what does not work for me.

I expect (`Xalan xml/test2.xml xml/test2.xslt` result):
```
<?xml version="1.0" encoding="utf-8"?>
<dat:dataPack xmlns:dat="http://www.stormware.cz/schema/version_2/data.xsd" xmlns:int="http://www.stormware.cz/schema/version_2/intDoc.xsd">
    <int:head>XSLT in Rust</int:head>
    <int:body>A simple document.</int:body>
</dat:dataPack>

```
But I only get:
```
<dataPack>
    <head>XSLT in Rust</head>
    <body>A simple document.</body>
</dataPack>

```

Thank you for answer.

**Comment by ballsteve** [comment]
Yes, this is a critical issue.

As a first step I'll make sure there is a test in the test suite for this issue.

As part of the release process, we'll make sure that all tests pass.

**Comment by ballsteve** [comment]
I've added a test for this issue on branch issue-58.

**Comment by ballsteve** [comment]
The test in branch issue-58 has been implemented and the test now passes.
Once this branch has been merged the issue can be closed.

**Comment by ballsteve** [comment]
Latest release includes this fix
