### ISSUE TITLE
Tree Equality

### ISSUE THREAD

**Issue by ballsteve** [ballsteve/xrust#83]
So for the tree comparison, you want to know if two trees represent the same XML Infoset? I'll see if I can use the PartialEq trait for that. Otherwise, I can define a comparison method on the Node trait.

_Originally posted by @ballsteve in https://github.com/ballsteve/xrust/issues/82#issuecomment-2208083469_

**Comment by ballsteve** [comment]
While thinking about PartialEq for smite, there are various options that one may want to apply to the comparison. For example, ignoring whitespace (i.e. text nodes that only contain whitespace characters). We could add a method to the Node trait that allows options, such as 'eq_with_options'.

**Comment by ballsteve** [comment]
Do we want to be able to compare trees that have different concrete implementations? For example, a smite tree compared to a intmuttree tree?

**Comment by Devasta** [comment]
Tbh I think we can get away with only comparing smite with smite, we will only be using it in one place: the XML.parser tests, where we compare a parsed document with a DTD against it's canonical XML equivalent.

**Comment by ballsteve** [comment]
It's actually pretty easy to do the comparison generically, as a default implementation in the Node trait. iow, I've done that and just testing it now

**Comment by ballsteve** [comment]
Done. The branch 'partialeq' has an implementation of the PartialEq trait for smite. It actually specifies PartialEq as a super trait of item::Node, and then provides a default implementation in the trait, utilising the generic methods to navigate the trees. However, that doesn't work for smite since it is Rc<Node> so it has its own implementation.
